### ISSUE TITLE
加载出bug

### ISSUE THREAD

**Issue by H3ll0W0lrd** [bit4woo/Fiora#10]
![image](https://user-images.githubusercontent.com/30374511/153752627-79bb29e7-5cb2-4c8e-997f-8a317788be52.png)
一加载就这样

**Comment by bit4woo** [comment]
是加载这个插件出现的问题？请查看是否有错误输出，以便定位问题

**Comment by bit4woo** [comment]
新的burp加载时确实有这个问题，感谢指出，已修复
