### ISSUE TITLE
mac下search 用不了

### ISSUE THREAD

**Issue by safe6Sec** [bit4woo/Fiora#2]
![image](https://user-images.githubusercontent.com/26316334/148035749-18741ecf-8e9a-4758-b3ad-403777a48404.png)
![image](https://user-images.githubusercontent.com/26316334/148035777-146e9878-10dd-4995-855c-a22c9fb2c1f4.png)

**Comment by bit4woo** [comment]
已修复，可自行编译最新代码使用
